/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sulibagakent.Screens;
import DbConnection.DBConnection;
import DbConnection.UserDAO;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author USER
 */
public class AddUser extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddUser.class.getName());
    
    /**
     * Creates new form AddUser
     */
    private UsersManagement usersManagement;

    public AddUser(java.awt.Frame parent, UsersManagement usersManagement) {
    super(parent, true); // modal dialog
    this.usersManagement = usersManagement;
    initComponents();
    setLocationRelativeTo(parent);
        
}
private boolean usernameExists(String username) {
    String sql = "SELECT 1 FROM users WHERE username = ?";
    try (Connection con = DBConnection.getConnection();
         PreparedStatement ps = con.prepareStatement(sql)) {

        ps.setString(1, username);
        try (ResultSet rs = ps.executeQuery()) {
            return rs.next();
        }
    } catch (Exception e) {
        e.printStackTrace();
        return true; // safest: treat as exists if error
    }
}
    private void registerUser(String role, String fullName, String username, String password) {
    String sql = "INSERT INTO users(role, full_name, username, password) VALUES (?,?,?,?)";

    try (Connection con = DBConnection.getConnection();
         PreparedStatement ps = con.prepareStatement(sql)) {

        ps.setString(1, role);
        ps.setString(2, fullName);
        ps.setString(3, username);
        ps.setString(4, password); // plain text for school demo

        ps.executeUpdate();
    } catch (Exception e) {
        throw new RuntimeException(e);
    }
}
    private boolean editMode = false;
private String originalUsername = null;

    public void setEditMode(String role, String username, String first, String last,
                        String email, String contact, String status) {

    editMode = true;
    originalUsername = username;

    // fill fields
    cmbRole.setSelectedItem(role);
    txtUsername.setText(username);
    txtFirstName.setText(first);
    txtLastName.setText(last);
    txtEmail.setText(email);
    txtContactNumber.setText(contact);

    // you don't have status field in AddUser UI right now
    // so we won't edit status unless you add a combo box.
    // password: optional to change during edit
    txtPassword.setText("");
    txtConfirmPassword.setText("");

    // lock username during edit (recommended)
    txtUsername.setEnabled(false);

    // change button text + title
    btnRegister.setText("Save Changes");
    jLabel1.setText("Update User");
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmbRole = new javax.swing.JComboBox<>();
        txtUsername = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtContactNumber = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        txtConfirmPassword = new javax.swing.JPasswordField();
        backbtn = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        logoutBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(650, 500));
        setMinimumSize(new java.awt.Dimension(650, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(247, 252, 250));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 550));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cashier", "Inventory Staff" }));
        cmbRole.addActionListener(this::cmbRoleActionPerformed);
        jPanel1.add(cmbRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 180, 40));
        jPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 180, 40));

        txtFirstName.addActionListener(this::txtFirstNameActionPerformed);
        jPanel1.add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 180, 40));

        txtLastName.addActionListener(this::txtLastNameActionPerformed);
        jPanel1.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 180, 40));

        txtEmail.addActionListener(this::txtEmailActionPerformed);
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 180, 40));
        jPanel1.add(txtContactNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 180, 40));

        txtPassword.addActionListener(this::txtPasswordActionPerformed);
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 180, 40));

        txtConfirmPassword.addActionListener(this::txtConfirmPasswordActionPerformed);
        jPanel1.add(txtConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, 180, 40));

        backbtn.setBackground(new java.awt.Color(94, 197, 168));
        backbtn.setText("Back");
        backbtn.addActionListener(this::backbtnActionPerformed);
        jPanel1.add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, -1, 30));

        btnRegister.setBackground(new java.awt.Color(94, 197, 168));
        btnRegister.setText("Register");
        btnRegister.addActionListener(this::btnRegisterActionPerformed);
        jPanel1.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, -1, 30));

        jLabel2.setText("Role:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel6.setText("Username:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel7.setText("Fist Name: ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel11.setText("Last Name:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jLabel14.setText("Email: ");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, -1));

        jLabel3.setText("Contact Number: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, -1, -1));

        jLabel4.setText("Password:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, 10));

        jLabel5.setText("Confirm password:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, -1, 20));

        jPanel2.setBackground(new java.awt.Color(94, 197, 168));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoutBtn.setBackground(new java.awt.Color(109, 213, 180));
        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(this::logoutBtnActionPerformed);
        jPanel2.add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 40, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sulibagakent/Icons/logo.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 70));

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel1.setText("Register New User");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRoleActionPerformed

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfirmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConfirmPasswordActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        LoginScreen ls = new LoginScreen();
        ls.show();
        this.dispose();
    }//GEN-LAST:event_backbtnActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
      String role = cmbRole.getSelectedItem().toString().trim();
    String firstName = txtFirstName.getText().trim();
    String lastName  = txtLastName.getText().trim();
    String email     = txtEmail.getText().trim();
    String contact   = txtContactNumber.getText().trim();
    String username  = txtUsername.getText().trim();

    // Required fields
    if (role.isEmpty() || firstName.isEmpty() || lastName.isEmpty() || username.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill in all required fields.");
        return;
    }

    // -------------------------
    // ✅ EDIT MODE (UPDATE)
    // -------------------------
    if (editMode) {

        // Optional password update: only if user typed something
        String password = new String(txtPassword.getPassword()).trim();
        String confirm  = new String(txtConfirmPassword.getPassword()).trim();

        if (!password.isEmpty() || !confirm.isEmpty()) {
            if (!password.equals(confirm)) {
                JOptionPane.showMessageDialog(this, "Passwords do not match!");
                return;
            }
            // If you want password update too, you need a DAO method for it.
            // For now: ignore password update.
        }

        // Status not in your form, so keep it as Active by default OR leave as-is
        String status = "Active";

        boolean ok = UserDAO.updateUserByUsername(username, role, firstName, lastName, email, contact, status);

        if (ok) {
            JOptionPane.showMessageDialog(this, "User updated successfully!");
            if (usersManagement != null) usersManagement.refreshUsers();
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Update failed.");
        }

        return;
    }

    // -------------------------
    // ✅ ADD MODE (REGISTER)
    // -------------------------
    String password = new String(txtPassword.getPassword()).trim();
    String confirm  = new String(txtConfirmPassword.getPassword()).trim();

    if (password.isEmpty() || confirm.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Password is required.");
        return;
    }

    if (!password.equals(confirm)) {
        JOptionPane.showMessageDialog(this, "Passwords do not match!");
        return;
    }

    if (UserDAO.usernameExists(username)) {
        JOptionPane.showMessageDialog(this, "Username already taken!");
        return;
    }

    try {
        UserDAO.addUser(role, firstName, lastName, username, password, email, contact);
        JOptionPane.showMessageDialog(this, "Registered successfully!");
        if (usersManagement != null) usersManagement.refreshUsers();
        this.dispose();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Registration failed: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to logout?", "Logout",JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if(confirm == JOptionPane.YES_OPTION){
            LoginScreen l = new LoginScreen();
            l.setVisible(true);
            this.dispose();
        }else{
        }
    }//GEN-LAST:event_logoutBtnActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JButton btnRegister;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JTextField txtContactNumber;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
