/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sulibagakent.Screens;

import javax.swing.JOptionPane;
import DbConnection.ProductDAO;
import DbConnection.ActivityDAO;
import java.sql.SQLException;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.awt.CardLayout;
import java.awt.BorderLayout;
import sulibagakent.CurrentUser;

/**
 *
 * @author Sulibaga-Ke
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
   
private CardLayout card;
private javax.swing.JPanel contentPanel; // this will hold the screens

    public Dashboard() {
        initComponents();
        jLabel5.setText("Welcome, ");
        refreshRecentActivity();
    }

    // ✅ constructor with firstName (for login)
    public Dashboard(String firstName) {
        initComponents();
        jLabel5.setText("Welcome, " + CurrentUser.firstName);
        refreshRecentActivity();
    }

    

public void refreshRecentActivity() {
    try {
        DefaultTableModel model = (DefaultTableModel) tblRecentActivity.getModel();
        model.setRowCount(0);

        List<Object[]> rows = ActivityDAO.fetchLatest(10);
        for (Object[] r : rows) {
            model.addRow(r);
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Load recent activity failed: " + e.getMessage());
    }
}


   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Products = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnInventory = new javax.swing.JLabel();
        jlabel = new javax.swing.JLabel();
        Controller = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnUsers = new javax.swing.JLabel();
        Reports = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel11 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblTtlProducts = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblLowStock = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblOutOfStock = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        lblSalesToday = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btnAddProduct = new javax.swing.JButton();
        btnStockIn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRecentActivity = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(247, 252, 250));
        setMinimumSize(new java.awt.Dimension(740, 700));
        setPreferredSize(new java.awt.Dimension(1250, 850));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(94, 197, 168));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Products.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sulibagakent/Icons/products.png"))); // NOI18N
        Products.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductsMouseClicked(evt);
            }
        });
        Products.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ProductsKeyPressed(evt);
            }
        });
        jPanel1.add(Products, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel2.setText("PRODUCTS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        btnInventory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sulibagakent/Icons/inventory.png"))); // NOI18N
        btnInventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInventoryMouseClicked(evt);
            }
        });
        jPanel1.add(btnInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jlabel.setText("INVENTORY");
        jPanel1.add(jlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));

        Controller.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sulibagakent/Icons/control-center.png"))); // NOI18N
        Controller.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ControllerMouseClicked(evt);
            }
        });
        jPanel1.add(Controller, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, -1));

        jLabel6.setText("POST CONTROLLER");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, -1));

        jLabel8.setText("REPORTS");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, -1, -1));

        jLabel9.setText("USERS");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 60, -1, -1));

        btnUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sulibagakent/Icons/group.png"))); // NOI18N
        btnUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUsersMouseClicked(evt);
            }
        });
        jPanel1.add(btnUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, -1, -1));

        Reports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sulibagakent/Icons/report.png"))); // NOI18N
        Reports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReportsMouseClicked(evt);
            }
        });
        jPanel1.add(Reports, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, -1, -1));

        logoutBtn.setBackground(new java.awt.Color(109, 213, 180));
        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        jPanel1.add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 40, 80, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));
        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, -10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Welcome, ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 40, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 90));

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel1.setText("DASHBOARD OVERVIEW");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 290, 30));

        jPanel2.setBackground(new java.awt.Color(94, 197, 168));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 160, 70));

        jLabel3.setText("Total Products");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        lblTtlProducts.setText("[ ]");
        jPanel2.add(lblTtlProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 210, 80));

        jPanel3.setBackground(new java.awt.Color(94, 197, 168));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 160, 70));

        jLabel4.setText("Low Stock");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        lblLowStock.setText("[ ]");
        jPanel3.add(lblLowStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 210, 80));

        jPanel6.setBackground(new java.awt.Color(94, 197, 168));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("Out of Stock");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        lblOutOfStock.setText("[ ] ");
        jPanel6.add(lblOutOfStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, 210, 80));

        jPanel7.setBackground(new java.awt.Color(94, 197, 168));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setText("Sales Today");
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        lblSalesToday.setText("[ ]");
        jPanel7.add(lblSalesToday, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 200, 210, 80));

        jPanel8.setBackground(new java.awt.Color(94, 197, 168));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setText("QUICK ACTIONS");
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        btnAddProduct.setBackground(new java.awt.Color(109, 213, 180));
        btnAddProduct.setText("+ Add Product");
        btnAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductActionPerformed(evt);
            }
        });
        jPanel8.add(btnAddProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        btnStockIn.setBackground(new java.awt.Color(109, 213, 180));
        btnStockIn.setText("+ Stock In");
        btnStockIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStockInActionPerformed(evt);
            }
        });
        jPanel8.add(btnStockIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 110, -1));

        jButton3.setBackground(new java.awt.Color(109, 213, 180));
        jButton3.setText("Start POS");
        jPanel8.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 110, -1));

        jButton4.setBackground(new java.awt.Color(109, 213, 180));
        jButton4.setText("View Reports");
        jPanel8.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 110, -1));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 480, 150));

        jPanel9.setBackground(new java.awt.Color(94, 197, 168));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setText("ALERTS / NOTIFICATIONS");
        jPanel9.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 320, 480, 150));

        jPanel10.setBackground(new java.awt.Color(94, 197, 168));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setText("RECENT ACTIVITY");
        jPanel10.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        tblRecentActivity.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Action", "Details", "User", "Date"
            }
        ));
        jScrollPane1.setViewportView(tblRecentActivity);

        jPanel10.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 1090, 240));

        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 1110, 280));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
    int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to logout?", "Logout",JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
    if(confirm == JOptionPane.YES_OPTION){
           LoginScreen l = new LoginScreen();
    l.setVisible(true);
    this.dispose();
    }else{
    }
    
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void ProductsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ProductsKeyPressed

   
    }//GEN-LAST:event_ProductsKeyPressed

    private void ProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductsMouseClicked
     ProductsManagement p = new ProductsManagement();
    p.setVisible(true);
    this.setVisible(false);


    }//GEN-LAST:event_ProductsMouseClicked

    private void btnInventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInventoryMouseClicked
    InventoryManagement inv = new InventoryManagement();
    inv.setVisible(true);
    this.setVisible(false); 
    }//GEN-LAST:event_btnInventoryMouseClicked

    private void btnUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsersMouseClicked
    UsersManagement u = new UsersManagement();
    u.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_btnUsersMouseClicked

    private void btnStockInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStockInActionPerformed
ProductStockingFrame psf = new ProductStockingFrame(this);
    psf.show();
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnStockInActionPerformed

    private void ReportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportsMouseClicked
    Reports rp = new Reports();
    rp.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_ReportsMouseClicked

    private void ControllerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ControllerMouseClicked
    Controller con = new Controller();
    con.show();
    this.dispose();
    }//GEN-LAST:event_ControllerMouseClicked

    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
    
    }//GEN-LAST:event_btnAddProductActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Controller;
    private javax.swing.JLabel Products;
    private javax.swing.JLabel Reports;
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JLabel btnInventory;
    private javax.swing.JButton btnStockIn;
    private javax.swing.JLabel btnUsers;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jlabel;
    private javax.swing.JLabel lblLowStock;
    private javax.swing.JLabel lblOutOfStock;
    private javax.swing.JLabel lblSalesToday;
    private javax.swing.JLabel lblTtlProducts;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JTable tblRecentActivity;
    // End of variables declaration//GEN-END:variables

}
